[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Base crate for extrs"
edition = "2021"
include = ["Cargo.toml", "src/**/*.rs"]
license = "Apache-2.0"
name = "ext-common"
repository = "https://github.com/extrs/ext"
version = "0.1.0"

[dependencies]
